globs:
  - "docs/**/*.md"
gitignore: true

config:
  # Not worth worrying about.
  code-block-style: false
  line-length: false

  # May not play well with mkdocs processing.
  no-bare-urls: false
  link-image-reference-definitions: false

  # Take care fixing.
  no-trailing-punctuation: false
  single-title: false

  # Better code blocks. Be the change you want to see in the world.
  commands-show-output: true
  fenced-code-language: true
