config:
  # Not worth worrying about.
  code-block-style: false
  commands-show-output: false
  line-length: false

  # May not play well with mkdocs processing.
  no-bare-urls: false
  reference-links-images: false
  link-image-reference-definitions: false

  # Take care fixing.
  fenced-code-language: false
  no-trailing-punctuation: false
  single-title: false
