version: 2.1

orbs:
  flox: flox/orb@1.0.0

workflows:
  build-docs:
    machine:
      image: ubuntu-2204:current
    jobs:
      - checkout
      - flox/install
      - flox/activate:
          command: mkdocs build
